/**
 *
 * @author  Esraa
 */
package texasPoker;

import java.awt.event.ActionListener;
import java.util.Arrays;

public class GamePage extends javax.swing.JFrame {
    
    public GamePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        computerBestHand = new javax.swing.JLabel();
        playerBestHand = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        computerDecision = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonHelp = new javax.swing.JButton();
        jLabelPlayerCard1 = new javax.swing.JLabel();
        jLabelComputerCard1 = new javax.swing.JLabel();
        difficultyLevel = new javax.swing.JComboBox<>();
        jLabelPlayerCard2 = new javax.swing.JLabel();
        jLabelComputerCard2 = new javax.swing.JLabel();
        jTextFieldDisplayWinner = new javax.swing.JLabel();
        jLabelCommunityCard1 = new javax.swing.JLabel();
        jLabelCommunityCard2 = new javax.swing.JLabel();
        jLabelPlayerName = new javax.swing.JLabel();
        jLabelCommunityCard3 = new javax.swing.JLabel();
        jLabelCommunityCard4 = new javax.swing.JLabel();
        jLabelCommunityCard5 = new javax.swing.JLabel();
        jButtonRaise = new javax.swing.JButton();
        jButtonFold = new javax.swing.JButton();
        jTextFieldRaise = new javax.swing.JTextField();
        jTextFieldPlayerBet = new javax.swing.JTextField();
        jTextFieldComputerBet = new javax.swing.JTextField();
        jButtonNewRound = new javax.swing.JButton();
        jButtonCall = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldWinner = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 90, 40));

        computerBestHand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        computerBestHand.setForeground(new java.awt.Color(255, 255, 255));
        computerBestHand.setText("...");
        jLayeredPane1.add(computerBestHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, 40));

        playerBestHand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playerBestHand.setForeground(new java.awt.Color(255, 255, 255));
        playerBestHand.setText("...");
        jLayeredPane1.add(playerBestHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 110, 40));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("The player1 has:");
        jLayeredPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 110, 20));

        computerDecision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        computerDecision.setForeground(new java.awt.Color(255, 255, 0));
        computerDecision.setText("Dicision");
        jLayeredPane1.add(computerDecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 10, 40));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("The player2 has:");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 130, -1));

        jButtonHelp.setBackground(new java.awt.Color(255, 255, 204));
        jButtonHelp.setText("Help?");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 70, 40));

        jLabelPlayerCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelPlayerCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 70, 100));

        jLabelComputerCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/53.png"))); // NOI18N
        jLayeredPane1.add(jLabelComputerCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 70, 100));

        difficultyLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Mesium", "Hard" }));
        difficultyLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyLevelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(difficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabelPlayerCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelPlayerCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 70, 100));

        jLabelComputerCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/53.png"))); // NOI18N
        jLayeredPane1.add(jLabelComputerCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 70, 100));

        jTextFieldDisplayWinner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldDisplayWinner.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDisplayWinner.setText("...");
        jLayeredPane1.add(jTextFieldDisplayWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 190, 120));

        jLabelCommunityCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelCommunityCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, 100));

        jLabelCommunityCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelCommunityCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 70, 100));

        jLabelPlayerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPlayerName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPlayerName.setText("Player name");
        jLayeredPane1.add(jLabelPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 90, -1));

        jLabelCommunityCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelCommunityCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 70, 100));

        jLabelCommunityCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelCommunityCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 70, 100));

        jLabelCommunityCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/52.png"))); // NOI18N
        jLayeredPane1.add(jLabelCommunityCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 70, 100));

        jButtonRaise.setBackground(new java.awt.Color(153, 0, 153));
        jButtonRaise.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRaise.setText("Raise");
        jButtonRaise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaiseActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonRaise, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 90, 40));

        jButtonFold.setBackground(new java.awt.Color(153, 0, 153));
        jButtonFold.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFold.setText("Fold");
        jButtonFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoldActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonFold, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 90, 40));

        jTextFieldRaise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRaiseActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextFieldRaise, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 90, 20));

        jTextFieldPlayerBet.setText("0");
        jTextFieldPlayerBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlayerBetActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextFieldPlayerBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 40, 30));

        jTextFieldComputerBet.setText("0");
        jTextFieldComputerBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComputerBetActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextFieldComputerBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 40, 30));

        jButtonNewRound.setBackground(new java.awt.Color(153, 0, 153));
        jButtonNewRound.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNewRound.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNewRound.setText("Start HERE");
        jButtonNewRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewRoundActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonNewRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 130, 70));

        jButtonCall.setBackground(new java.awt.Color(153, 0, 153));
        jButtonCall.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCall.setText("Next Step");
        jButtonCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCallActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonCall, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("THE WINNER IS:");
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 110, 30));

        jTextFieldWinner.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldWinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texasPoker/images/IMG-9534.jpg"))); // NOI18N
        jLayeredPane1.add(jTextFieldWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 840, 530));

        jLabel13.setText("jLabel13");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Cards");
        jLayeredPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPlayerBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlayerBetActionPerformed
       
    }//GEN-LAST:event_jTextFieldPlayerBetActionPerformed

    private void jTextFieldComputerBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComputerBetActionPerformed
      
    }//GEN-LAST:event_jTextFieldComputerBetActionPerformed

    private void jButtonNewRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewRoundActionPerformed

    }//GEN-LAST:event_jButtonNewRoundActionPerformed

    private void jButtonFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoldActionPerformed
    
    }//GEN-LAST:event_jButtonFoldActionPerformed

    private void jTextFieldRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRaiseActionPerformed
       
    }//GEN-LAST:event_jTextFieldRaiseActionPerformed

    private void jButtonRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaiseActionPerformed
        
    }//GEN-LAST:event_jButtonRaiseActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        
        HelpingPage window = new HelpingPage();
        window.setVisible(true);
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void difficultyLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyLevelActionPerformed
        
    }//GEN-LAST:event_difficultyLevelActionPerformed

    private void jButtonCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCallActionPerformed
     
    }//GEN-LAST:event_jButtonCallActionPerformed

    public void setPlayerCard1(int cardNmuber){
        jLabelPlayerCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    
    public void setPlayerCard2(int cardNmuber){
        jLabelPlayerCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    
    public void setComputerCard1(int cardNmuber){
        jLabelComputerCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    
    public void setComputerCard2(int cardNmuber){
        jLabelComputerCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    
    public void setCommunityCard1(int cardNmuber){
        jLabelCommunityCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    public void setCommunityCard2(int cardNmuber){
        jLabelCommunityCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    public void setCommunityCard3(int cardNmuber){
        jLabelCommunityCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    public void setCommunityCard4(int cardNmuber){
        jLabelCommunityCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    public void setCommunityCard5(int cardNmuber){
        jLabelCommunityCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texaspoker/images/"+String.valueOf(cardNmuber)+".png")));
    }
    
    public void addjButtonNewRound(ActionListener listener){
        jButtonNewRound.addActionListener(listener);
    }
    
    public void addjButtonRaise(ActionListener listener){
        jButtonRaise.addActionListener(listener);
    }
    public void addjButtonCall(ActionListener listener){
        jButtonCall.addActionListener(listener);
    }
    public void addjButtonFold(ActionListener listener){
        jButtonFold.addActionListener(listener);
    }

    
    public void setPlayerName(String name){
        jLabelPlayerName.setText(name);
    }
    public void setPlayerBestHand(String name){
        playerBestHand.setText(name);
    }
    public void setPlayer2BestHand(String name){
        computerBestHand.setText(name);
    }
    
    public int getPlayerBet(){
        return Integer.parseInt(jTextFieldRaise.getText());
    }
    
    public void setPlayerBet(String bet){
        jTextFieldPlayerBet.setText(bet);
    }
    
    public void setComputerBet(String bet){
        jTextFieldComputerBet.setText(bet);
    }
    
    public void setDisplayWinner (String text){
        jTextFieldDisplayWinner.setText(text);
    }
    
    public void setcomputerDecision(String text){
        computerDecision.setText(text);
    }
    
    public String getDifficultyLevel(){
        return difficultyLevel.getSelectedItem().toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computerBestHand;
    private javax.swing.JLabel computerDecision;
    private javax.swing.JComboBox<String> difficultyLevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCall;
    private javax.swing.JButton jButtonFold;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonNewRound;
    private javax.swing.JButton jButtonRaise;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabelCommunityCard1;
    private javax.swing.JLabel jLabelCommunityCard2;
    private javax.swing.JLabel jLabelCommunityCard3;
    private javax.swing.JLabel jLabelCommunityCard4;
    private javax.swing.JLabel jLabelCommunityCard5;
    private javax.swing.JLabel jLabelComputerCard1;
    private javax.swing.JLabel jLabelComputerCard2;
    private javax.swing.JLabel jLabelPlayerCard1;
    private javax.swing.JLabel jLabelPlayerCard2;
    private javax.swing.JLabel jLabelPlayerName;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextFieldComputerBet;
    private javax.swing.JLabel jTextFieldDisplayWinner;
    private javax.swing.JTextField jTextFieldPlayerBet;
    private javax.swing.JTextField jTextFieldRaise;
    private javax.swing.JLabel jTextFieldWinner;
    private javax.swing.JLabel playerBestHand;
    // End of variables declaration//GEN-END:variables
}
